### ISSUE TITLE
Using MQTT Client in a Lambda

### ISSUE THREAD

**Issue by claytantor** [aws/aws-iot-device-sdk-python#185]
Hey All,
This could be a "help wanted" issue, or it may be a bug so if someone has done this before and knows its not a bug tell me and  I will reissue.

I have written a simple publish client intended to be run in a lambda, happy to share:

https://gist.github.com/claytantor/d76c893e97b5c7031523e0f380454c90 

```
def initIOT(config):
    myMQTTClient = AWSIoTMQTTClient(config['iot']['iot_id'])
    myMQTTClient.configureEndpoint(config['iot']['mqqt_endpoint'], 8883)
    myMQTTClient.configureCredentials(
        make_fullpath(config['iot']['credentials']['root_ca_path']),
        make_fullpath(config['iot']['credentials']['private_key_path']),
        make_fullpath(config['iot']['credentials']['cert_path']))

    #myMQTTClient connection configuration
    myMQTTClient.configureAutoReconnectBackoffTime(1, 32, 20)
    myMQTTClient.configureOfflinePublishQueueing(-1)  # Infinite offline Publish queueing
    myMQTTClient.configureDrainingFrequency(2)  # Draining: 2 Hz
    myMQTTClient.configureConnectDisconnectTimeout(10)  # 10 sec
    myMQTTClient.configureMQTTOperationTimeout(5)  # 5 sec
    # Connect and subscribe to AWS IoT
    myMQTTClient.connect()
    return myMQTTClient
```
and a publish method

```
def publish(myMQTTClient, config, messageModel):
    print("publishing message to topic:{0}".format(config['iot']['mqqt_led_message_topic']))
    messageJson = json.dumps(messageModel)
    myMQTTClient.publish(config['iot']['mqqt_led_message_topic'], messageJson, 1)
    print('Published topic %s: %s\n' % (config['iot']['mqqt_led_message_topic'], messageJson))

```
my configs:

```
  iot:
      iot_id: claytantor-flashlexpi32-1
      mqqt_endpoint: unique-ats.iot.us-east-1.amazonaws.com
      mqqt_port: 8883
      mqqt_led_message_topic: ledticker-iot-message-dev
      credentials:
          root_ca_path: keys/AmazonRootCA1.pem
          private_key_path: keys/unique-private.pem.key
          cert_path: keys/unique-certificate.pem.crt
```
The intention is to allow the Lambda to send messages to the IOT device which is subscribed to the same MQTT queue.

The issue is that both the Lambda and the PI work for the first period of initialization, and then when the period ends they stop interacting. My backoff settings seem to be realistic and I would expect that both attempt to reconnect, but they seem to just stop working. I am guessing that either there is something about the Lambda and the way it works internally that causes this or that I have the backoff misconfigured on the PI, or both. 

Any insight is appreciated.

Clay
